name: '@ngneat/helipopper'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        env:
          HUSKY_SKIP_INSTALL: 'true'
      - run: npm i

      - name: Build playground app in production mode
        run: npm run build:playground

      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          start: npm run serve:playground:static
          wait-on: http://localhost:4200

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        env:
          HUSKY_SKIP_INSTALL: 'true'
      - run: npm i

      - name: Build library
        run: npm run build:lib
